# Generated by Django 4.2.16 on 2024-10-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='group_images')),
            ],
        ),
        migrations.CreateModel(
            name='SekaiWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, upload_to='sekai_images')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('animation', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='song_images')),
                ('song_url', models.URLField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekai_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='sekai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekai_app.sekaiworld'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='event_images')),
                ('start_date', models.DateField()),
                ('end_date', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekai_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sekai_type', models.CharField(choices=[('Virtual Singer', 'Virtual Singer'), ('Game Character', 'Game Character')], max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='character_images')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekai_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('1★', '1★'), ('2★', '2★'), ('3★', '3★'), ('4★', '4★'), ('Limited', 'Limited')], max_length=10)),
                ('stats', models.JSONField(blank=True)),
                ('image_url', models.ImageField(blank=True, upload_to='card_images')),
                ('is_limited', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekai_app.character')),
            ],
        ),
    ]
