# Generated by Django 4.2.16 on 2024-10-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='theme',
        ),
        migrations.AlterField(
            model_name='character',
            name='sekai_type',
            field=models.CharField(choices=[('Game Character', 'Game Character'), ('Virtual Singer', 'Virtual Singer')], max_length=255),
        ),
    ]
