# Generated by Django 4.2.16 on 2024-10-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0002_remove_group_theme_alter_character_sekai_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='stats',
            field=models.TextField(),
        ),
    ]
